services:
  nexus-node:
    container_name: nexus-node
    image: ghcr.io/haitovs/nexus-node:latest
    build: .
    restart: always
    network_mode: host
    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/nexus-node/cert.pem"
      SERVICE_PORT: "62050"
      XRAY_API_PORT: "62051"
      SERVICE_PROTOCOL: "rest"
    volumes:
      - /var/lib/nexus-node:/var/lib/nexus-node
